### ISSUE TITLE
Build a getter/splitter and tests

### ISSUE THREAD

**Issue by krwenholz** [krwenholz/wort#3]
* Create a function that takes in a hash, gets a key out of it, and splits the content on common split characters.
* Write tests.
* Pick a nice testing framework (for outputting).

**Comment by KristopherPaulsen** [comment]
Isn't this what I just did with my previous branch? I think I'm misunderstanding the issue here ¯\\_(ツ)_/¯

**Comment by krwenholz** [comment]
This is exactly what your branch is accomplishing :)

I just wanted to write it down in an issue so we can keep track of our TODO list. You can just close the issue once you merge your branch.

**Comment by KristopherPaulsen** [comment]
Oh good haha, totally thought I was having memory issues for a moment
